# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adam/workspace/openGL/games/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adam/workspace/openGL/games/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/workspace/openGL/games/engine/CMakeFiles /home/adam/workspace/openGL/games/engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adam/workspace/openGL/games/engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named atomic

# Build rule for target.
atomic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atomic
.PHONY : atomic

# fast build rule for target.
atomic/fast:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/build
.PHONY : atomic/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f bin/CMakeFiles/uninstall.dir/build.make bin/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f bin/src/CMakeFiles/glfw.dir/build.make bin/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) -f bin2/CMakeFiles/glew.dir/build.make bin2/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named glew_s

# Build rule for target.
glew_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew_s
.PHONY : glew_s

# fast build rule for target.
glew_s/fast:
	$(MAKE) -f bin2/CMakeFiles/glew_s.dir/build.make bin2/CMakeFiles/glew_s.dir/build
.PHONY : glew_s/fast

#=============================================================================
# Target rules for targets named visualinfo

# Build rule for target.
visualinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visualinfo
.PHONY : visualinfo

# fast build rule for target.
visualinfo/fast:
	$(MAKE) -f bin2/CMakeFiles/visualinfo.dir/build.make bin2/CMakeFiles/visualinfo.dir/build
.PHONY : visualinfo/fast

#=============================================================================
# Target rules for targets named glewinfo

# Build rule for target.
glewinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glewinfo
.PHONY : glewinfo

# fast build rule for target.
glewinfo/fast:
	$(MAKE) -f bin2/CMakeFiles/glewinfo.dir/build.make bin2/CMakeFiles/glewinfo.dir/build
.PHONY : glewinfo/fast

src/bordered_rectangle.o: src/bordered_rectangle.cpp.o

.PHONY : src/bordered_rectangle.o

# target to build an object file
src/bordered_rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/bordered_rectangle.cpp.o
.PHONY : src/bordered_rectangle.cpp.o

src/bordered_rectangle.i: src/bordered_rectangle.cpp.i

.PHONY : src/bordered_rectangle.i

# target to preprocess a source file
src/bordered_rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/bordered_rectangle.cpp.i
.PHONY : src/bordered_rectangle.cpp.i

src/bordered_rectangle.s: src/bordered_rectangle.cpp.s

.PHONY : src/bordered_rectangle.s

# target to generate assembly for a file
src/bordered_rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/bordered_rectangle.cpp.s
.PHONY : src/bordered_rectangle.cpp.s

src/color.o: src/color.cpp.o

.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/element_buffer.o: src/element_buffer.cpp.o

.PHONY : src/element_buffer.o

# target to build an object file
src/element_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/element_buffer.cpp.o
.PHONY : src/element_buffer.cpp.o

src/element_buffer.i: src/element_buffer.cpp.i

.PHONY : src/element_buffer.i

# target to preprocess a source file
src/element_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/element_buffer.cpp.i
.PHONY : src/element_buffer.cpp.i

src/element_buffer.s: src/element_buffer.cpp.s

.PHONY : src/element_buffer.s

# target to generate assembly for a file
src/element_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/element_buffer.cpp.s
.PHONY : src/element_buffer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/point.o: src/point.cpp.o

.PHONY : src/point.o

# target to build an object file
src/point.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/point.cpp.o
.PHONY : src/point.cpp.o

src/point.i: src/point.cpp.i

.PHONY : src/point.i

# target to preprocess a source file
src/point.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/point.cpp.i
.PHONY : src/point.cpp.i

src/point.s: src/point.cpp.s

.PHONY : src/point.s

# target to generate assembly for a file
src/point.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/point.cpp.s
.PHONY : src/point.cpp.s

src/rectangle.o: src/rectangle.cpp.o

.PHONY : src/rectangle.o

# target to build an object file
src/rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/rectangle.cpp.o
.PHONY : src/rectangle.cpp.o

src/rectangle.i: src/rectangle.cpp.i

.PHONY : src/rectangle.i

# target to preprocess a source file
src/rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/rectangle.cpp.i
.PHONY : src/rectangle.cpp.i

src/rectangle.s: src/rectangle.cpp.s

.PHONY : src/rectangle.s

# target to generate assembly for a file
src/rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/rectangle.cpp.s
.PHONY : src/rectangle.cpp.s

src/rectangle_parent.o: src/rectangle_parent.cpp.o

.PHONY : src/rectangle_parent.o

# target to build an object file
src/rectangle_parent.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/rectangle_parent.cpp.o
.PHONY : src/rectangle_parent.cpp.o

src/rectangle_parent.i: src/rectangle_parent.cpp.i

.PHONY : src/rectangle_parent.i

# target to preprocess a source file
src/rectangle_parent.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/rectangle_parent.cpp.i
.PHONY : src/rectangle_parent.cpp.i

src/rectangle_parent.s: src/rectangle_parent.cpp.s

.PHONY : src/rectangle_parent.s

# target to generate assembly for a file
src/rectangle_parent.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/rectangle_parent.cpp.s
.PHONY : src/rectangle_parent.cpp.s

src/shader.o: src/shader.cpp.o

.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/square.o: src/square.cpp.o

.PHONY : src/square.o

# target to build an object file
src/square.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/square.cpp.o
.PHONY : src/square.cpp.o

src/square.i: src/square.cpp.i

.PHONY : src/square.i

# target to preprocess a source file
src/square.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/square.cpp.i
.PHONY : src/square.cpp.i

src/square.s: src/square.cpp.s

.PHONY : src/square.s

# target to generate assembly for a file
src/square.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/square.cpp.s
.PHONY : src/square.cpp.s

src/texture.o: src/texture.cpp.o

.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i

.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s

.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/vertex_array.o: src/vertex_array.cpp.o

.PHONY : src/vertex_array.o

# target to build an object file
src/vertex_array.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/vertex_array.cpp.o
.PHONY : src/vertex_array.cpp.o

src/vertex_array.i: src/vertex_array.cpp.i

.PHONY : src/vertex_array.i

# target to preprocess a source file
src/vertex_array.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/vertex_array.cpp.i
.PHONY : src/vertex_array.cpp.i

src/vertex_array.s: src/vertex_array.cpp.s

.PHONY : src/vertex_array.s

# target to generate assembly for a file
src/vertex_array.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/vertex_array.cpp.s
.PHONY : src/vertex_array.cpp.s

src/vertex_buffer.o: src/vertex_buffer.cpp.o

.PHONY : src/vertex_buffer.o

# target to build an object file
src/vertex_buffer.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/vertex_buffer.cpp.o
.PHONY : src/vertex_buffer.cpp.o

src/vertex_buffer.i: src/vertex_buffer.cpp.i

.PHONY : src/vertex_buffer.i

# target to preprocess a source file
src/vertex_buffer.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/vertex_buffer.cpp.i
.PHONY : src/vertex_buffer.cpp.i

src/vertex_buffer.s: src/vertex_buffer.cpp.s

.PHONY : src/vertex_buffer.s

# target to generate assembly for a file
src/vertex_buffer.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/vertex_buffer.cpp.s
.PHONY : src/vertex_buffer.cpp.s

src/window.o: src/window.cpp.o

.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i

.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s

.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/atomic.dir/build.make CMakeFiles/atomic.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... atomic"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... glew"
	@echo "... glew_s"
	@echo "... visualinfo"
	@echo "... glewinfo"
	@echo "... src/bordered_rectangle.o"
	@echo "... src/bordered_rectangle.i"
	@echo "... src/bordered_rectangle.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/element_buffer.o"
	@echo "... src/element_buffer.i"
	@echo "... src/element_buffer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/point.o"
	@echo "... src/point.i"
	@echo "... src/point.s"
	@echo "... src/rectangle.o"
	@echo "... src/rectangle.i"
	@echo "... src/rectangle.s"
	@echo "... src/rectangle_parent.o"
	@echo "... src/rectangle_parent.i"
	@echo "... src/rectangle_parent.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/square.o"
	@echo "... src/square.i"
	@echo "... src/square.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/vertex_array.o"
	@echo "... src/vertex_array.i"
	@echo "... src/vertex_array.s"
	@echo "... src/vertex_buffer.o"
	@echo "... src/vertex_buffer.i"
	@echo "... src/vertex_buffer.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

